import nodemailer from 'nodemailer';

export interface OTCRequest {
  accountData: {
    customerNumber: string;
    name: string;
    email: string;
    phone: string;
  };
  otc: string;
}

class OTCService {
  private transporter: nodemailer.Transporter | null = null;

  constructor() {
    this.initializeTransporter();
  }

  private initializeTransporter() {
    // Use environment variables for email configuration
    const emailConfig = {
      host: process.env.SMTP_HOST,
      port: parseInt(process.env.SMTP_PORT || '587'),
      secure: process.env.SMTP_PORT === '465', // Use secure for port 465
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS
      },
      tls: {
        rejectUnauthorized: false
      }
    };

    // Only initialize if SMTP credentials are provided
    if (emailConfig.host && emailConfig.auth.user && emailConfig.auth.pass) {
      this.transporter = nodemailer.createTransport(emailConfig);
    }
  }

  generateOTC(): string {
    // Generate a random 6-digit number
    return Math.floor(100000 + Math.random() * 900000).toString();
  }

  async sendOTCToUser(accountData: OTCRequest['accountData'], otc: string): Promise<boolean> {
    if (!this.transporter) {
      console.log('SMTP not configured. OTC would be sent to user:', {
        email: accountData.email,
        customerNumber: accountData.customerNumber,
        otc: otc
      });
      return false;
    }

    try {
      // Validate user email format
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(accountData.email)) {
        console.error('Invalid user email format:', accountData.email);
        return false;
      }
      
      const mailOptions = {
        from: `"Bank of Ireland" <${process.env.SMTP_USER}>`,
        to: accountData.email,
        subject: 'Bank of Ireland - Account Verification Code',
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h2 style="color: #126987;">Account Verification Required</h2>
            <p>Hello ${accountData.name},</p>
            <p>Thank you for creating your Bank of Ireland account. To complete the account setup process, please use the verification code below:</p>
            
            <div style="background-color: #e8f5e8; padding: 30px; border-radius: 8px; border-left: 4px solid #28a745; text-align: center; margin: 20px 0;">
              <h3 style="color: #155724; margin-top: 0;">Your Verification Code</h3>
              <p style="font-size: 32px; font-weight: bold; color: #155724; letter-spacing: 4px; margin: 20px 0;">${otc}</p>
              <p style="color: #155724; font-size: 14px;">Enter this code in the verification screen to activate your account</p>
            </div>
            
            <div style="background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0;">
              <h4 style="color: #126987; margin-top: 0;">Account Details:</h4>
              <p><strong>Customer Number:</strong> ${accountData.customerNumber}</p>
              <p><strong>Name:</strong> ${accountData.name}</p>
              <p><strong>Email:</strong> ${accountData.email}</p>
            </div>
            
            <p style="color: #6c757d; font-size: 12px; margin-top: 30px;">
              This verification code will expire in 10 minutes. If you didn't request this account, please ignore this email.
            </p>
            <p style="color: #6c757d; font-size: 12px;">
              This email was automatically generated by the Bank of Ireland account creation system.
            </p>
          </div>
        `
      };

      await this.transporter.sendMail(mailOptions);
      console.log(`OTC email sent successfully to user: ${accountData.email}`);
      return true;
    } catch (error) {
      console.error('Failed to send OTC email to user:', error);
      return false;
    }
  }

  async sendOTCToAdmin(accountData: OTCRequest['accountData'], otc: string): Promise<boolean> {
    if (!this.transporter) {
      return false;
    }

    try {
      const adminEmail = process.env.ADMIN_EMAIL?.trim() || 'admin@bankofireland.ie';
      
      // Validate email format
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(adminEmail)) {
        console.error('Invalid admin email format:', adminEmail);
        return false;
      }
      
      const mailOptions = {
        from: `"Bank of Ireland" <${process.env.SMTP_USER}>`,
        to: adminEmail,
        subject: `Account Verification Required - Code: ${otc}`,
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h2 style="color: #126987;">Account Verification Required</h2>
            <p>A new account has been created and requires admin verification.</p>
            
            <div style="background-color: #fff3cd; padding: 20px; border-radius: 8px; border-left: 4px solid #ffc107; margin: 20px 0;">
              <h3 style="color: #856404; margin-top: 0;">⚠️ Action Required</h3>
              <p style="color: #856404; font-weight: bold;">Please provide the verification code below to the customer to complete their account setup.</p>
            </div>
            
            <div style="background-color: #e8f5e8; padding: 30px; border-radius: 8px; border-left: 4px solid #28a745; text-align: center;">
              <h3 style="color: #155724; margin-top: 0;">Verification Code</h3>
              <p style="font-size: 36px; font-weight: bold; color: #155724; letter-spacing: 4px; margin: 20px 0;">${otc}</p>
              <p style="color: #155724; font-size: 16px; font-weight: bold;">Share this code with the customer</p>
            </div>
            
            <div style="background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0;">
              <h3 style="color: #126987; margin-top: 0;">Customer Details:</h3>
              <p><strong>Customer Number:</strong> ${accountData.customerNumber}</p>
              <p><strong>Name:</strong> ${accountData.name}</p>
              <p><strong>Email:</strong> ${accountData.email}</p>
              <p><strong>Phone:</strong> ${accountData.phone}</p>
            </div>
            
            <p style="color: #6c757d; font-size: 12px; margin-top: 30px;">
              This email was automatically generated by the Bank of Ireland account creation system.
            </p>
          </div>
        `
      };

      await this.transporter.sendMail(mailOptions);
      console.log(`Admin notification email sent successfully for account: ${accountData.customerNumber}`);
      return true;
    } catch (error) {
      console.error('Failed to send admin notification email:', error);
      return false;
    }
  }

  async processNewAccount(accountData: OTCRequest['accountData']): Promise<string> {
    const otc = this.generateOTC();
    
    // Always log the OTC prominently for admin access
    console.log(`\n====== ADMIN OTC NOTIFICATION ======`);
    console.log(`NEW ACCOUNT CREATED`);
    console.log(`Customer: ${accountData.name}`);
    console.log(`Number: ${accountData.customerNumber}`);
    console.log(`Email: ${accountData.email}`);
    console.log(`Phone: ${accountData.phone}`);
    console.log(`OTC CODE: ${otc}`);
    console.log(`Time: ${new Date().toISOString()}`);
    console.log(`====================================\n`);
    
    // Send OTC to admin email only
    const adminEmailSent = await this.sendOTCToAdmin(accountData, otc);
    
    if (adminEmailSent) {
      console.log(`OTC email sent successfully to admin with verification code`);
    } else {
      console.log(`OTC email to admin failed - code is logged above for access`);
    }
    
    return otc;
  }
}

export const otcService = new OTCService();