import nodemailer from 'nodemailer';

export interface OTCRequest {
  accountData: {
    customerNumber: string;
    name: string;
    email: string;
    phone: string;
  };
  otc: string;
}

class OTCService {
  private transporter: nodemailer.Transporter | null = null;

  constructor() {
    this.initializeTransporter();
  }

  private initializeTransporter() {
    // Use environment variables for email configuration
    const emailConfig = {
      host: process.env.SMTP_HOST,
      port: parseInt(process.env.SMTP_PORT || '587'),
      secure: process.env.SMTP_SECURE === 'true',
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS
      }
    };

    // Only initialize if SMTP credentials are provided
    if (emailConfig.host && emailConfig.auth.user && emailConfig.auth.pass) {
      this.transporter = nodemailer.createTransport(emailConfig);
    }
  }

  generateOTC(): string {
    // Generate a random 6-digit number
    return Math.floor(100000 + Math.random() * 900000).toString();
  }

  async sendOTC(accountData: OTCRequest['accountData'], otc: string): Promise<boolean> {
    if (!this.transporter) {
      console.log('SMTP not configured. OTC would be sent:', {
        customerNumber: accountData.customerNumber,
        name: accountData.name,
        otc: otc
      });
      return false;
    }

    try {
      const adminEmail = process.env.ADMIN_EMAIL || 'admin@bankofireland.ie';
      
      const mailOptions = {
        from: process.env.SMTP_USER,
        to: adminEmail,
        subject: `New Account Created - OTC: ${otc}`,
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h2 style="color: #126987;">New Bank Account Created</h2>
            <p>A new account has been created in the Bank of Ireland system.</p>
            
            <div style="background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0;">
              <h3 style="color: #126987; margin-top: 0;">Account Details:</h3>
              <p><strong>Customer Number:</strong> ${accountData.customerNumber}</p>
              <p><strong>Name:</strong> ${accountData.name}</p>
              <p><strong>Email:</strong> ${accountData.email}</p>
              <p><strong>Phone:</strong> ${accountData.phone}</p>
            </div>
            
            <div style="background-color: #e8f5e8; padding: 20px; border-radius: 8px; border-left: 4px solid #28a745;">
              <h3 style="color: #155724; margin-top: 0;">One-Time Code (OTC)</h3>
              <p style="font-size: 24px; font-weight: bold; color: #155724; letter-spacing: 2px;">${otc}</p>
              <p style="color: #155724; font-size: 14px;">This code is for administrative purposes only.</p>
            </div>
            
            <p style="color: #6c757d; font-size: 12px; margin-top: 30px;">
              This email was automatically generated by the Bank of Ireland account creation system.
            </p>
          </div>
        `
      };

      await this.transporter.sendMail(mailOptions);
      console.log(`OTC email sent successfully for account: ${accountData.customerNumber}`);
      return true;
    } catch (error) {
      console.error('Failed to send OTC email:', error);
      return false;
    }
  }

  async processNewAccount(accountData: OTCRequest['accountData']): Promise<string> {
    const otc = this.generateOTC();
    
    // Send the OTC email
    await this.sendOTC(accountData, otc);
    
    // Log the OTC generation for audit purposes
    console.log(`OTC generated for new account: ${accountData.customerNumber} - Code: ${otc}`);
    
    return otc;
  }
}

export const otcService = new OTCService();